# Generated by Django 3.2.5 on 2023-02-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zip', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_to_customers', to='masterapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ponumber', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('batch_number', models.IntegerField(max_length=100, null=True)),
                ('manufacturing_date', models.DateField(null=True)),
                ('exp_date', models.DateField(null=True)),
                ('License_Number', models.IntegerField(max_length=100, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.company')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ponumber', models.IntegerField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Shipping', 'Shipping'), ('Closed', 'Closed'), ('Fullyreleased', 'Fullyreleased')], default='Draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_order_name', models.CharField(max_length=40)),
                ('date', models.DateField(null=True)),
                ('createdby', models.CharField(max_length=100)),
                ('status', models.CharField(default='Shipping', max_length=100)),
                ('po', models.CharField(max_length=40, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterapp.company')),
                ('ponumber', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='products_to_shipping', to='masterapp.products')),
            ],
        ),
    ]
