# Generated by Django 3.2.5 on 2022-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0002_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
