# Generated by Django 3.2.5 on 2022-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_alter_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(default='Shipping', max_length=100),
        ),
    ]
