# Generated by Django 3.2.5 on 2023-01-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_alter_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='po',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
