# Generated by Django 3.2.5 on 2023-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0005_shipping_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='License_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='batch_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
