# Generated by Django 3.2.5 on 2023-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0006_auto_20230125_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exp_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
