# Generated by Django 3.2.5 on 2023-01-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0007_auto_20230128_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manufacturing_date',
        ),
    ]
