# Generated by Django 3.2.5 on 2023-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0008_auto_20230128_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exp_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturing_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
