# Generated by Django 3.2.5 on 2023-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0011_auto_20230128_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='License_Number',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='batch_number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
