# Generated by Django 3.2.16 on 2022-12-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('date_birth', models.DateField(null=True)),
                ('age', models.CharField(default='age', max_length=100)),
                ('place', models.CharField(default='place', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField(default='address')),
                ('mobile', models.CharField(default='phone', max_length=100)),
                ('date_join', models.DateField(null=True)),
                ('eduqu', models.CharField(default='qualification', max_length=100)),
                ('userRole', models.CharField(default='admin', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
                ('conpass', models.CharField(default='confirm password', max_length=100)),
                ('dummy1', models.CharField(default='dummy1', max_length=100)),
                ('dummy2', models.CharField(default='dummy2', max_length=100)),
                ('dummy3', models.CharField(default='dummy3', max_length=100)),
                ('dummy4', models.CharField(default='dummy4', max_length=100)),
                ('key', models.CharField(default='key', max_length=500)),
            ],
        ),
    ]
