# Generated by Django 3.2.5 on 2023-01-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelname', models.CharField(max_length=100)),
                ('savedid', models.CharField(max_length=100)),
                ('operationdone', models.CharField(max_length=100)),
                ('donebyuser', models.CharField(max_length=100)),
                ('donebyUserRole', models.CharField(max_length=100)),
                ('doneDateTime', models.DateTimeField(max_length=100)),
            ],
        ),
    ]
