# Generated by Django 3.2.5 on 2022-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SapProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ponumber', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Shipping', 'Shipping'), ('Closed', 'Closed'), ('Fullyreleased', 'Fullyreleased')], default='Draft', max_length=20)),
            ],
        ),
    ]
